### ISSUE TITLE
Agregar el WIP (Work in Progress) commit

### ISSUE THREAD

**Issue by pakgva** [jansanchez/commits#1]

**Comment by jansanchez** [comment]
Pedro, cuentame mas detalles sobre eso por favor.

osea que parte del estandar sea por ejemplo un commit como este:

wip(main): creando controladores en php

**Comment by pakgva** [comment]
El wip commit puede servir para subir al repositorio remoto para que se hagan revisiones de código por partes. De tal forma, que no se espera a que se termina toda la tarea para revisar, sino se puede ir revisando mientras se va desarrollando la tarea. De tal forma que la revisión de código no es tan tediosa.

**Comment by jansanchez** [comment]
I understand, perfect.

**Comment by jansanchez** [comment]
Entonces con ese cambio, podrias cerrar el issue por favor?

**Comment by jansanchez** [comment]
cool! gracias Pedrisho! facil que podriamos realizar una revision actual de los estandares de commit.

http://chris.beams.io/posts/git-commit/

http://www.slideshare.net/TarinGamberini/commit-messages-goodpractices

FYI
